### ISSUE TITLE
Coordinates must be within the United States

### ISSUE THREAD

**Issue by B0RJA** [jDeters-USACE/Antecedent-Precipitation-Tool#17]
Is it possible to use the APT outside the USA in countries with GHCN-Daily coverage?

Now I get the error: Coordinates must be within the United States!

This is a snapshot of the GHCN-Daily stations including Spain, the country in which I am interested. 

![image](https://user-images.githubusercontent.com/1688261/126942597-87bd06fe-f42b-4445-8fab-534153798559.png)

Thank you for sharing your work!

Best regards,
Borja

**Comment by jlgutenson** [comment]
Hey Borja, 

We haven't tested outside of the U.S., but if you run the APT using the source code you should be able to bypass the U. S. requirement.

Check out the bottom of https://github.com/jDeters-USACE/Antecedent-Precipitation-Tool/blob/master/arc/anteProcess.py. This script runs the bulk of the APT analysis. 

Looking at your plot of GHCN-Daily stations, you may need to increases the search distance from your location of interest to the nearest GHCN-Daily station (https://github.com/jDeters-USACE/Antecedent-Precipitation-Tool/blob/master/arc/anteProcess.py#L1036).

Thanks,
Joseph
