### ISSUE TITLE
Program will not open or place desktop icon

### ISSUE THREAD

**Issue by dibar-c** [jDeters-USACE/Antecedent-Precipitation-Tool#2]
Hi, I and at least one other person are having an issue where the tool opens the terminal and the license agreement, but once we check the box and hit submit the software closes out and does not create the desktop icon.

**Comment by KSully-CAD** [comment]
Hi, I am having this same issue with 3 people in our office, we are running Windows 10. am I missing a prerequisite, compatibility or some other item? There was nothing I could find in the documentation, and it is being required on a project. 
Please help!

**Comment by spatche** [comment]
Did you guys ever figure it out? I am getting the following error

C:\TempPath\Antecedent-Precipitation-Tool-master\Antecedent-Precipitation-Tool-master\update>"Antecedent Precipitation Tool.exe"
Error loading Python DLL 'C:\TempPath\Antecedent-Precipitation-Tool-master\Antecedent-Precipitation-Tool-master\update\python36.dll'.
LoadLibrary: The specified module could not be found.

**Comment by jlgutenson** [comment]
Hey @dibar-c, @KSully-CAD, and @spatche, are you still having the issues you've noted above?

**Comment by dibar-c** [comment]
Hi, yes we are still having the issue over here, I was able to find that it's something in our environment though - I was able to run the software on a personal computer with no issues. I suspect firewall/antivirus/proxy issues but I'm struggling to narrow down what exactly is shooting it down. The error has the following:

> urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded 
> with url: /jDeters-USACE/Antecedent-Precipitation-Tool/master/v/wbd (Caused by SSLError(SSLError(1, '[SSL: 
> CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)'),))

Which seems to indicate an issue with verifying the ssl cert, maybe you could provide any url's the software might be reaching out to so we can be sure they're whitelisted?

Do you have any other ideas on what might be preventing us from launching?

**Comment by KSully-CAD** [comment]
We were finally able to get it running, Forcepoint would not allow connection even with the whitelist. Perhaps USACE could take the additional step of registering the software with the security vendors?  This would make it much easier.

**Comment by jlgutenson** [comment]
It looks like the 'raw.githubusercontent.com' is the site that needs to be whitelisted. Each time the APT executable is ran it makes a call back to this URL to check for an update and to automatically update, if available. That seems to be what is causing the issue.

**Comment by jlgutenson** [comment]
@dibar-c, did whitelisting 'raw.githubusercontent.com' get things working on your end?

**Comment by dibar-c** [comment]
Yes, from my understanding our security team ended up having to make an exception in the DNS rules in our proxy/webfilter. Once they did this the executable got zapped once again by our antivirus (we had to make 4-5 separate exceptions in the antivirus) but we're up and running now. Thanks!

**Comment by jlgutenson** [comment]
@dibar-c , I'm glad you got it working! Sounds like the antivirus issue is related to what was reported in Issue #5. We're still looking into that.

**Comment by DDemko-CLLC** [comment]
This app will not launch.  I tried whitelisting.  I do not know how to edit DSN filters for this site.  Please advise on how to do this or if there is another fix .  Thank you.

**Comment by dibar-c** [comment]
@DDemko-CLLC Do you (or your company) use a proxy service for web filtering? That's where the DNS settings will need to be adjusted.

**Comment by DDemko-CLLC** [comment]
Not that I am aware of.  I found proxy settings in windows 10.  I'm using a local wireless internet service which shows two DNS addresses.  The linksys settings are set to random hardware address and IP assignment is Auto (DHCP).  I can use manual IP setting populate the DNS settings. Not sure what to add or if is where to fix the problem? Thank you.

**Comment by DDemko-CLLC** [comment]
> @dibar-c , I'm glad you got it working! Sounds like the antivirus issue is related to what was reported in Issue #5. We're still looking into that.

Hi, my client ask me to help get this program up and running because it is now a requirement.  I have not been able to get the app exe. to open or run.  Windows 10 does not open the error notice.  I have disabled filters in my router with no luck. Do you have a work flow to troubleshoot this? Thank you.

**Comment by jlgutenson** [comment]
If you experience similar issues and you've whitelisted the IP and adjusted your antivirus settings, try reinstalling the software from scratch using these directions https://github.com/jDeters-USACE/Antecedent-Precipitation-Tool/releases/tag/v1.0.13. When you install make that you don't bury the path too deep into a particular directory. A safe bet may be to install place the APT onto your Desktop.

**Comment by JeffLaramy** [comment]
I just installed this to the Desktop in my office and can get anything to happen.  I run the *.exe, a shell appears for a few seconds but can't see any text or anything.  Shell goes away after a few seconds and no shortcut appears on the desktop.  Where so the error logs go?  I suspect it might be a firewall issue after reading the other comments above so will install it on a personal computer tomorrow and see if that works.

**Comment by jlgutenson** [comment]
Glad you got it working @JeffLaramy!

**Comment by JeffLaramy** [comment]
Thank you @jlgutenson !  I also worked with our IT deparment and it's working on our office computers now too.  They said it was being blocked by Umbrella DNS.

**Comment by jlgutenson** [comment]
Great @JeffLaramy! Thank you for letting us know.
