### ISSUE TITLE
main_ex doesn't open application

### ISSUE THREAD

**Issue by aekendig** [jDeters-USACE/Antecedent-Precipitation-Tool#21]
I can move this issue/question to a different location if this isn't appropriate. I've followed the installation instructions on the erdc GitHub and am able to open the Antecedent Precipitation Tool directory from my desktop. When I double click main_ex.exe a command prompt window opens and closes quickly. I'm not seeing Antecedent Precipitation Tool.exe anywhere. I'm working on a Windows 10 64-bit system.

**Comment by jlgutenson** [comment]
Hey Amy,

This location is fine. Thank you for reaching out!

This may be an issue with your organizations IT security. The APT makes several calls back to Github to download several datasets and make sure that the APT version you're is the most up-to-date version. Some networks will not like an exe making those calls behind the scenes and will block them. 

Please have your IT folks whitelist those backend calls to Github. 

If that doesn't do the trick, just let us know!

Thanks,
Joseph Gutenson
