### ISSUE TITLE
NED EPQS Server Offline Error

### ISSUE THREAD

**Issue by cfrees** [jDeters-USACE/Antecedent-Precipitation-Tool#23]
I received the following error when attempting to use the APT tool today. It appears that the USGS EPQS that the APT is pulling from has been retired as of March 1, 2023. (https://ned.usgs.gov/epqs/)

#######################################################################################################################
#######################################################################################################################
Original - National Map Variant:
  -Test URL: https://nationalmap.gov/epqs/pqs.php?x=-121.5&y=38.5&output=json&units=Feet
  -Attempting to connect (15-second timeout)
Querying https://nationalmap.gov/epqs...

    ############################################
    # --- National Map EPQS Server Offline --- #
    ############################################

New Mirror - National Elevation Dataset (NED) Variant:
  -Test URL: https://ned.usgs.gov/epqs/pqs.php?x=-121.5&y=38.5&units=Feet&output=json
  -Attempting to connect (15-second timeout)
Querying https://ned.usgs.gov/epqs...

    ###################################
    # --- NED EPQS Server Offline --- #
    ###################################

The APT cannot complete this analysis.

The following error occurred. Please close the APT and reboot.

Exception in Tkinter callback
Traceback (most recent call last):
  File "arc\anteProcess.py", line 207, in test_usgs_epqs_servers
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tkinter\__init__.py", line 1705, in __call__
  File "arc\ant_GUI.py", line 742, in calculate_and_graph
  File "arc\ant_GUI.py", line 791, in get_inputs_unique
  File "arc\ant_GUI.py", line 1215, in calculate_or_add_batch
  File "arc\anteProcess.py", line 379, in __init__
  File "arc\anteProcess.py", line 225, in test_usgs_epqs_servers
Exception: The APT is unable to run if both USGS Elevation Point Query Services are offline.

**Comment by jlgutenson** [comment]
Hi @cfrees, 

My apologies that you’ve been having trouble utilizing the APT!

It seems that the USGS data service that the APT uses to determine elevation is down.

I’ve let the USGS know. I’m not sure when it will be back up but it’s usually not down longer than a few days.

Thanks,
Joseph

**Comment by tburnett604** [comment]
I had this problem as well. When I go to the USGS Elevation Point Query Services website it says that the application was retired as of March 1, 2023. It seems the URL has been updated but the APT tool is still trying to access the expired URL.

**Comment by jlgutenson** [comment]
Hi @cfrees and @tburnett604 ,

Apologies for the delayed response!

The newest version of the APT can be downloaded at this link: https://github.com/erdc/Antecedent-Precipitation-Tool/releases/tag/v1.0.23. This version should address the issues you've encountered. 

If you have any questions or issues, just let us know!

Thanks,
Joseph
