### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by brayn185** [jDeters-USACE/Antecedent-Precipitation-Tool#24]
Keep getting error PROJ: proj_identify: cannot find proj.db
Unsure if this has something to do with the error posted last week but any help would be greatly appreciated. This is my first time using Antecedent so it could certainly be an operator error. 

Thanks,
B

**Comment by jlgutenson** [comment]
Hi @brayn185,

Apologies for the delayed response!

The newest version of the APT can be downloaded at this link: https://github.com/erdc/Antecedent-Precipitation-Tool/releases/tag/v1.0.23. This version should address the issues you've encountered.

If you have any questions or issues, just let us know!

Thanks,
Joseph
