### ISSUE TITLE
'Exception in Tkinter callback' Error

### ISSUE THREAD

**Issue by cfrees** [jDeters-USACE/Antecedent-Precipitation-Tool#29]
Hello, I am receiving the following error when running the APT Tool for the following coordinates and date: 45.365728, -93.373603, May 14, 2024. I have tried closing the APT Tool and rebooting and I'm still getting this error. Coordinates from a different part of Minnesota with the same date input worked just fine. 

No suitable station available to replace null values.
Attempting linear interpolation to fill null values...
542 null values remaining.
Unfortunately, data gaps still persist after interpolating. Therefore, the APT was unable to complete your analysis.
-----------------------------------------------------------------------------------------------------------------------

Null values remain after interpolation... the APT cannot complete this analysis

The APT cannot complete this analysis.

The following error occurred. Please close the APT and reboot.

Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1892, in __call__
  File "arc\ant_GUI.py", line 774, in calculate_and_graph
  File "arc\ant_GUI.py", line 842, in get_inputs_unique
  File "arc\ant_GUI.py", line 1353, in calculate_or_add_batch
  File "arc\anteProcess.py", line 592, in setInputs
  File "arc\anteProcess.py", line 1191, in createFinalDF
RuntimeError: No active exception to reraise

**Comment by jlgutenson** [comment]
Hi @cfrees, 

I'm sorry your having APT troubles!

In this case, you may want to utilize the gridded precipitation dataset, as it seems there isn't enough station data near this location. 

If your troubles persist, email APT-Report-Issue@usace.army.mil and they can assist you further.

Thanks,
Joseph
