### ISSUE TITLE
NOAA's Server is Offline

### ISSUE THREAD

**Issue by dtollette** [jDeters-USACE/Antecedent-Precipitation-Tool#30]
Attempting to run the APT, however requests have been terminated because weather data is currently inaccessible (NOAA's server is offline).

**Comment by jlgutenson** [comment]
Hi @dtollette,

My apologies! I just now saw this.

Please let the support team now if you're still having issues. They can be reached at APT-Report-Issue@usace.army.mil

Thanks,
Joseph Gutenson
