### ISSUE TITLE
Missing components? Not able to connect. 

### ISSUE THREAD

**Issue by KSully-CAD** [jDeters-USACE/Antecedent-Precipitation-Tool#4]
I am getting the following errors, is there a way someone can connect me with the Library assets being called? see attached:
[error.txt](https://github.com/jDeters-USACE/Antecedent-Precipitation-Tool/files/5110153/error.txt)

**Comment by jlgutenson** [comment]
Hey @KSully-CAD, are you still having trouble? I noticed that in your error file that the APT is looking for the Python libraries on the D: drive. Have you installed the APT on an external drive? If so, it may be looking for libraries that are on the C: Drive but not the D: Drive.
